# Generated by Django 5.1.3 on 2024-11-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_called', models.DateTimeField()),
            ],
        ),
    ]
