# Generated by Django 5.1.3 on 2024-11-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='last_called',
            new_name='last_opened',
        ),
    ]
