# Generated by Django 5.1.3 on 2024-11-23 15:42

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_image_height_image_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='Original',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('last_opened', models.DateTimeField()),
                ('file', models.ImageField(upload_to=api.models.original_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=api.models.preview_upload_path)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.original')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('file', models.ImageField(upload_to=api.models.tile_upload_path)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.original')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
