# Generated by Django 5.1.3 on 2024-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_original_preview_scaletile_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='name',
        ),
        migrations.AddField(
            model_name='preview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
