# Generated by Django 5.1.3 on 2024-11-23 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_preview_name_preview_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='original',
            name='last_opened',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
