# Generated by Django 5.1.3 on 2024-11-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_original_last_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='preview',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='scaletile',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
