# Generated by Django 5.1.3 on 2024-11-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_preview_name_alter_scaletile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preview',
            name='name',
        ),
        migrations.RemoveField(
            model_name='scaletile',
            name='name',
        ),
    ]
